pipeline {
    agent {
        docker {
            image 'maven:3-jdk-8-alpine'
            args '-p 8081:8081'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean compile install'				
            }
        }
		stage ('Unit Test') {
			steps {
				sh 'mvn test'
			}
			post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
		}		
		stage ('Code analysis') {	
			steps {	
				sh 'mvn checkstyle:checkstyle verify -Dcheckstyle.config.location="checkstyle.xml"'
				step([$class: 'CheckStylePublisher',
                      canRunOnFailed: true,
                      defaultEncoding: '',
                      healthy: '100',
                      pattern: '**/target/checkstyle-result.xml',
                      unHealthy: '90',
                      useStableBuildAsReference: true
				])
			}
		}		
		stage ('Functional Test') {
			steps {
				sh 'echo Prueba funcionales punta a punta'
			}
			
		}
    }
}